export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_PROFILE = 'SET_PROFILE';
export const PROFILE_END = 'PROFILE_END';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const TOURNAMENT_START = 'TOURNAMENT_START';
export const TOURNAMENT_PAST_SUCCESS = 'TOURNAMENT_PAST_SUCCESS';
export const TOURNAMENT_UPCOMING_SUCCESS = 'TOURNAMENT_UPCOMING_SUCCESS';
export const TOURNAMENT_END = 'TOURNAMENT_END';
export const TOURNAMENT_SUCCESS = 'TOURNAMENT_SUCCESS';
export const MYTOURNAMENT_SUCCESS = 'MYTOURNAMENT_SUCCESS';
export const MYTOURNAMENT_DELETE = 'MYTOURNAMENT_DELETE';
export const MYPARTICIPATION_SUCCESS = 'MYPARTICIPATION_SUCCESS';
